dist: trusty
sudo: required
language: generic

before_cache:
  - rm -rf $HOME/.opam/log
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=1
  - OPAMJOBS=1
  - OPAMVERBOSE=1
  - OPAMYES=true
  - OCAML_VERSION="4.10.0"
  matrix:
  - TEST_TARGET="8.11.1"

before_script:
  -  ./ci/keep_alive.sh &

install:
  - opam init -n -y -c ${OCAML_VERSION}
  - eval $(opam config env)
  - opam config var root
  # this somehow fails the second time...
  - opam repo add coq-released http://coq.inria.fr/opam/released || true
  - opam install -y --verbose -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET} -y
  - opam install --deps-only .
  - opam upgrade -y --verbose -j ${NJOBS}

script:
  - eval $(opam config env)
  - opam config var root
  - opam install -t .
